version: "2.1"
services:
  mysql:
    build: ./docker-configs/database
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: starter_app
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    healthcheck:
      test: "exit 0"
    volumes:
      - ./docker-configs/database/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./docker-configs/database/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
  starter_app:
    build: .
    ports:
      - "3000:3000"
    environment: 
      - DB_HOST=mysql
    expose:
      - "3000"
    depends_on:
      mysql:
        condition: service_healthy
    command: node server.js